### PR TITLE
Add debounce time setting

### LINKED ISSUE #74: Switch turn off after 4seconds
I cant get it working. If I use the switch (switch.abend_stateful_scene) the switch turned off automatically after 4-5seconds.
I use version 1.2.1. I can't find any solution. Could you please help?

4c8c7bd55f0a03d073c96dc158ca06225f6cfb6d

### LINKED ISSUE #85: Stateful switch entity immediately turns off
After turning the switch on, it seems to immediately turn itself off... The lights all turn on correct and stay on despite the stateful switch turning off.  Only happens for some of the stateful switches, not all.  Anything I can look at to debug?

```
Kitchen - Medium Stateful Scene turned off triggered by service Switch: Turn on
7:23:44 PM - Now - admin
Kitchen - Medium Stateful Scene turned on triggered by service Switch: Turn on
7:23:44 PM - Now - admin

```

### PR DESCRIPTION
**Pull request by kdkavanagh**
Closes #85 and #37. 
Probably also closes #74

### CODE REVIEW

**Comment by Cheerpipe** [comment]
Hi.

Config flow is broken because you missed this two  const:

    CONF_DEBOUNCE_TIME
    DEFAULT_DEBOUNCE_TIME

**Comment by kdkavanagh** [comment]
Thanks, sorted.  Had missed them in porting over to the new code which was newer than what I was already running

**Comment by Cheerpipe** [comment]
so far so good. Using your PR with debounce time of 1 seconds do the trick.

Thanks.

**Comment by hugobloem** [comment]
Thank you!

**Pull request merged**
