### PR TITLE
fix: Fixed off scene select restoration reading unavailable data

### PR DESCRIPTION
**Pull request by cayossarian**
"None" is now at the top of the select list of off scenes.  Also this PR does not attempt to load scenes in the select that may not be populated yet.  In all cases all versions load the most current scenes.

This PR adds the off scene entity id as an extra attribute instead of relying on friendly name which is not guaranteed to be unique.  Falls back to friendly name on initial load (if previous config was v1.60) if that is all that is stored.  Going forward then the entity id is used.

### CODE REVIEW

**Comment by cayossarian** [comment]
sorry about the additional PR, I tested 1.60 locally and did not note a problem but hopefully this will help...makes more sense.  I may be able to spend some time and put more tests together...noted you started.

**Comment by hugobloem** [comment]
No problem. Thank you for addressing this. Shall I merge and release this now?

**Comment by cayossarian** [comment]
It’s disconcerting that some folks seem to have hangs - not sure if they tried to clear browser  cache.   I can’t reproduce a hang.  this pull request does address an issue and has backward compatibility with 1.60.  It’s better than leaving 1.61.

**Comment by cayossarian** [comment]
I uninstalled the integration, installed 1.60 upgraded through HACs to 1.61 just fine.  I then loaded this pull over the top of 1.6.1 and the integration works as well.  

The hang may not be related to this integration or they need clear the browser cache.  This PR puts the off scene 'None' at the top of the select and is backward compatible. so I think this PR is good and can be merged but I'm ok if you want to wait and test it.  Happy holiday!

**Comment by hugobloem** [comment]
Okay I'll merge and publish a release now.

**Pull request merged**
